<a href="https://colab.research.google.com/github/Elwing-Chou/tibame_night_20251120/blob/main/tibame20251220.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import json
import urllib.request as req
import pandas as pd

url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36632&geo=TW%2CHK"
f = req.urlopen(url)
content = f.read()
content = json.loads(content)

danmus = content["data"]["danmu"]
# pd: DataFrame表格 Series一列/一行
# json->dataframe
# [{}, {}, {}]
df = pd.DataFrame(danmus)
# 不要列標籤: index=False
df.to_csv("danmu.csv", encoding="utf-8")
df.to_excel("danmu.xlsx")
df

,text,color,size,position,time,sn,userid
0,二刷,#FFFFFF,1,0,0,42903755,qaz1210731
1,吉伊卡哇！,#FFFFFF,1,0,0,45641971,dodylee0107
2,感謝動畫瘋！,#FFFFFF,1,0,0,45796240,hyg125
3,2025.11.24簽,#FDE53D,1,0,0,47316552,MilkTea157
4,吉依好可愛,#FFFFFF,1,0,5,40580321,KingOrange69
...,...,...,...,...,...,...,...
524,ˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊ,#FFFFFF,1,0,893,46704569,swyan
525,我,#FFFFFF,1,0,897,45779317,Webb2012
526,😀,#00C3FC,1,0,898,40894473,kekerry75
527,沒了？？？？,#FFFFFF,1,0,901,42188563,linzzi
528,哈,#FF0026,1,0,901,44529579,st5109185



```
1. 過濾: 準備跟你資料依樣多的True(保留)/False(刪去)
2. 轉換

```

In [9]:
testdf = df.head(3)
fil = [True, False, False]
testdf[fil]

  text    color  size  position  time        sn      userid
0   二刷  #FFFFFF     1         0     0  42903755  qaz1210731

In [11]:
# 1 col
df["text"]
# multiple cols
df[["userid", "text"]]

           userid                 text
0      qaz1210731                   二刷
1     dodylee0107                吉伊卡哇！
2          hyg125               感謝動畫瘋！
3      MilkTea157          2025.11.24簽
4    KingOrange69                吉依好可愛
..            ...                  ...
524         swyan  ˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊˊ
525      Webb2012                    我
526     kekerry75                    😀
527        linzzi               沒了？？？？
528     st5109185                    哈

[529 rows x 2 columns]

In [ ]:
df["userid"].value_counts()

In [17]:
target = "tsubakilee"
fil = df["userid"] == target
df[fil]

                     text    color  size  position  time        sn      userid
157                 我第一次看  #FFFFFF     1         0   221  41164994  tsubakilee
172      有人在嗎嘉義\n\n有人在嗎+1  #FFFFFF     1         0   259  41165004  tsubakilee
342     有人跟我一樣晚上看嗎\n看了快餓死  #FFFFFF     1         0   576  41165019  tsubakilee
416  沒了？？？？？？？？？？？？？？？？？？  #FFFFFF     1         0   693  41165047  tsubakilee